version: 2.1

orbs:
  docker: circleci/docker@1.3.0

jobs:
  build-and-push:
    parameters:
      version:
        type: string
    executor: docker/docker
    environment:
      REGISTRY_HOST: harbor.k8s.libraries.psu.edu
      REGISTRY_URL: library/requests
      DOCKER_LOGIN: 'robot$circleci'
    steps:
    - setup_remote_docker
    - checkout
    - docker/check:
        registry: $REGISTRY_HOST
    - docker/build:
        image: $REGISTRY_URL
        registry: $REGISTRY_HOST
        tag: << parameters.version >>
    - docker/push:
        registry: $REGISTRY_HOST
        image: $REGISTRY_URL
        tag: << parameters.version >>

workflows:
  docker_push:
    jobs:
      - build-and-push:
          matrix:
            parameters:
              version: [ "$CIRCLE_SHA1" ]
          filters:
            branches:
              only:
                - master
                - /preview\/.*/
      - build-and-push:
          matrix:
            parameters:
              version: [ "$CIRCLE_TAG" ]
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /.*/